type = "webpack"
webpack_config = "webpack.config.js"

zone_id = "348792876bb474a7cadf69be26c00b5c"
account_id = "3e4e267fb0f575f02c3d6ecd0c65f3cd"

name = "dstn-shortener"
routes = ["dstn.to/*"]
workers_dev = false

kv_namespaces = [
  { binding = "SHORTENER_DSTN", id = "b5a30f1b1f064e46bded10759ed22d14", preview_id = "b5a30f1b1f064e46bded10759ed22d14" }
]

vars = { SHORTENER_UPSTREAM = "https://portfolio.dstn.to" }

[miniflare]
kv_persist = "redis://localhost:6379?db=9"

[env.dev]
name = "dstn-shortener-dev"
routes = ["w.dstn.to/*"]
workers_dev = false

kv_namespaces = [
  { binding = "SHORTENER_DSTN", id = "b5a30f1b1f064e46bded10759ed22d14", preview_id = "b5a30f1b1f064e46bded10759ed22d14" }
]

vars = { SHORTENER_UPSTREAM = "https://portfolio.dstn.to" }